# -*- coding: utf-8 -*-
"""Prueba.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OUzug-Wnko-KeLkgJr4znDz89WIlI1ee
"""

# Proyecto Introducción a Señales Biomédicas
print("Introduccion a Señales Biomedicas")





